version: '3'
services:
  app:
    container_name: app
    hostname: app
    
    build: 
      context: .
      dockerfile: Dockerfile.service
    ports:
      - 5000:5000
    restart: always
      
  mysql_db:
    container_name: mysql_db
    hostname: mysql_db
    image: mysql:8.1.0
    ports:
      - "32001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=app
      - MYSQL_PASSWORD=password123
      - MYSQL_USER=mainroot
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: