version: '3'
services:
  my_app:
    container_name: my_app
    hostname: my_app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5000
    links:
      - mysql_db
    restart: always
      
  mysql_db:
    image: mysql:8.1.0
    container_name: mysql_db
    hostname: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: forapp
      MYSQL_USER: mainroot
      MYSQL_PASSWORD: 12345678
    ports:
      - 3306:3306
    volumes:
      - forapp:/var/lib/mysql
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin:5.2.1
    restart: always
    links:
      - mysql_db
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_USER: mainroot
      PMA_PASSWORD: 12345678

volumes:
  forapp:
